### ISSUE TITLE
Build.PL does not specify SQL::Abstract as dependency

### ISSUE THREAD

**Issue by andk** [preaction/ETL-Yertl#153]
https://metacpan.org/source/PREACTION/ETL-Yertl-0.029/Build.PL#

All fails in 0.029 are due to missing SQL::Abstract. Sample fail report: http://www.cpantesters.org/cpan/report/85955703

The Makefile.PL is fine.

Regards,

**Comment by preaction** [comment]
This is fixed in v0.030 pushed to PAUSE. Thanks!
