### ISSUE TITLE
Future::IO dependency

### ISSUE THREAD

**Issue by jimeUWOshkosh** [preaction/ETL-Yertl#161]
Ubuntu 18.04: perlbrew v5.28.0

$ su - woot                        # my only user that can become root
$ sudo bash                        # I be root
$ source /opt/perlbrew/etc/bashrc  # point at system wide perlbrew

$ cpanm ETL::Yertl
Building and testing IO-Async-0.73 ... FAIL

$ sudo apt-get install -y libio-aio-perl

$ cpanm ETL::Yertl
...
Building and testing IO-Async-0.73 ... FAIL

build.log
   ...
   Building IO-Async
   ...
t/64handle-bind.t ............ ok
Can't locate Future/IO.pm in @INC (you may need to install the Future::IO module) (@INC contains: . /home/woot/.cpanm/work/1561582136.12560/IO-Async-0.73/blib/lib /home/woot/.cpanm/work/1561582136.12560/IO-Async-0.73/blib/arch /opt/perlbrew/perls/perl-5.28.0/lib/site_perl/5.28.0/x86_64-linux /opt/perlbrew/perls/perl-5.28.0/lib/site_perl/5.28.0 /opt/perlbrew/perls/perl-5.28.0/lib/5.28.0/x86_64-linux /opt/perlbrew/perls/perl-5.28.0/lib/5.28.0) at t/70future-io.t line 16.
BEGIN failed--compilation aborted at t/70future-io.t line 16.
t/70future-io.t ..............
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run
t/99pod.t .................... ok

$ cpanm Future::IO
$ cpanm ETL::Yertl

**Comment by preaction** [comment]
Thanks for the report! That looks like more of an IO::Async problem, which will be addressed in [IO::Async ticket #129807 in RT](https://rt.cpan.org/Public/Bug/Display.html?id=129807). Yertl doesn't rely on Future::IO, so I shouldn't fix it that way.
