### ISSUE TITLE
Issue with IO::Async since 0.74

### ISSUE THREAD

**Issue by tehmoth** [preaction/ETL-Yertl#164]
Since the IO::Async change 

> 0.74    2019-06-27 18:44:38
>         [CHANGES]
>          * Warn about IO::Async::Stream using autoflush on a blocking handle

ETL::Yertl's tests fail with 

>             #   Failed test 'nothing on stderr'
>             #   at t/bin/ygrok.t line 36.
>             # An IO::Async::Stream with autoflush needs an O_NONBLOCK write handle at /home/perl/.cpanm/work/1595835558.26327/ETL-Yertl-0.043/blib/lib/ETL/Yertl/Command/ygrok.pm line 189.
>             # Looks like you failed 1 test of 3.

forcing the installation to continue with notests, the command line tools ygrok, yfrom, yto throw the "An IO::Async::Stream with autoflush needs an O_NONBLOCK write handle" warning, but stillseem to do the right thing

Installing IO::Async@0.73 before installing ETL::Yertl  allows the tests to pass and no warnings to be thrown from the command line tools

**Comment by preaction** [comment]
Thanks for the report! I'm going to try just forcing the flag to fix this, though it seems that this may break Windows (not that I'm sure it ever worked...)
